# Importações

In [1]:
import numpy as np

# Operações Básicas com Vetores

In [2]:
# Criando vetores
u = np.array([1,3])
v = np.array([3,1])

In [3]:
# Soma  e Subtração
y = u + v
w = u - v

# Divisão e Multiplicação
a = u / v
b = u * v

# Produto escalar
alpha = 2
escalar = u * alpha

# Produto interno
interno = np.dot(u,v)

# Produto vetorial
u3 = np.array([1,3,1])
v3 = np.array([3,1,1])
vetorial = np.cross(u3,v3)

In [9]:
print(f'Soma: {y}')
print(f'Subtração: {w}')
print(f'Divisão: {a}')
print(f'Multiplicação: {b}')
print(f'Produto Escalar: {escalar}')
print(f'Produto Interno: {interno}')
print(f'Produto Vetorial: {vetorial}')

Soma: [4 4]
Subtração: [-2  2]
Divisão: [0.33333333 3.        ]
Multiplicação: [3 3]
Produto Escalar: [2 6]
Produto Interno: 6
Produto Vetorial: [ 2  2 -8]


# Operações Básicas com Matrizes

In [4]:
I = np.array([[1,0],[0,1]])
A = np.array([[2,1],[1,2]])

In [11]:
# Soma
B = A + I
print(f'Soma da matriz: \n {B}')

Soma da matriz: 
 [[3 1]
 [1 3]]


In [12]:
# Subtração
B = A - I
print(f'Subtração da matriz: \n {B}')

Subtração da matriz: 
 [[1 1]
 [1 1]]


In [13]:
# As matrizes não precisam ter a mesma dimensão
C = A + u
print(f'Soma da matriz A com o vetor u: \n {C}')

Soma da matriz A com o vetor u: 
 [[3 4]
 [2 5]]


In [14]:
# multiplicação de matrizes
D = np.matmul(A,I)
print(f'Multiplicação de Matrizes: \n {B}')

Multiplicação de Matrizes: 
 [[1 1]
 [1 1]]
